var NLRUM=NLRUM||{};NLRUM.validateClientScriptThreshold=function(a){return!(null===a||""===a||isNaN(a)||a<NLRUM.absoluteMinClientScriptDuration)};
NLRUM.getLoggingThreshold=function(){function a(b){var c=/(^| )telemetrySettings=([^;]+)/.exec(document.cookie);if(c){for(var d={},e,f=/(\w+):([^|]*)/g;e=f.exec(c);)d[e[1]]=unescape(e[2]);if(d[b])return d[b]}return""}return function(){var b=a("loggingOverrideStartTime");var c=a("loggingOverrideEndTime");if(NLRUM.validateClientScriptThreshold(b)&&NLRUM.validateClientScriptThreshold(c)){var d=(new Date).getTime();b=d>=b&&d<=c}else b=!1;return b&&(b=a("minClientScriptDuration"),NLRUM.validateClientScriptThreshold(b))?
b:NLRUM.minClientScriptDuration}()};NLRUM.clientScriptAsyncCallbackBegin=function(a,b,c){NLRUM.marks["ASYNC"+a+b+(c||"").toString()]=(new Date).getTime()};
NLRUM.clientScriptAsyncCallbackEnd=function(a,b,c,d,e){var f,h=c||"",g=NLRUM.marks["ASYNC"+a+b+h.toString()];NLRUM.marks["ASYNC"+a+b+h.toString()]=null;minClientScriptDuration=NLRUM.validateClientScriptThreshold(NLRUM.getLoggingThreshold())?NLRUM.getLoggingThreshold():NLRUM.minClientScriptDuration;"number"===typeof g&&(f=parseInt((new Date).getTime()-g,10))>=minClientScriptDuration&&NLRUM.processClientScriptTime(a,b,c,g,f,e,d,"true")};
NLRUM.clientScriptBegin=function(a,b,c){NLRUM.marks[a+b+(c||"").toString()]=(new Date).getTime()};NLRUM.clientScriptEnd=function(a,b,c,d,e){var f,h=c||"",g=NLRUM.marks[a+b+h.toString()];NLRUM.marks[a+b+h.toString()]=null;minClientScriptDuration=NLRUM.validateClientScriptThreshold(NLRUM.getLoggingThreshold())?NLRUM.getLoggingThreshold():NLRUM.minClientScriptDuration;"number"===typeof g&&(f=parseInt((new Date).getTime()-g,10))>=minClientScriptDuration&&NLRUM.processClientScriptTime(a,b,c,g,f,d,e,"false")};
NLRUM.processClientScriptTime=function(a,b,c,d,e,f,h,g){function l(m){if(isNaN(m))return m;m=parseInt(m,10);return 0>m?m:m-1}var k={};switch(a){case "pageInit":k.mode=c[0];break;case "lineInit":case "validateDelete":case "validateInsert":case "validateLine":k.sublistId=c[0];break;case "recalc":case "sublistChanged":k.sublistId=c[0];k.operation=c[1];break;case "postSourcing":k.sublistId=c[0];k.fieldId=c[1];k.line="1.0"===h?c[2]:l(c[2]);break;case "validateField":case "fieldChanged":k.sublistId=c[0];
k.fieldId=c[1];k.line="1.0"===h?c[2]:l(c[2]);k.column="1.0"===h?c[3]:l(c[3]);break;case "saveRecord":break;default:return}k.trigger=a;k.scriptId=b;k.startTime=d;k.executionTime=e;k.recordType=f;k.runtimeVersion=h;k.url=window.location.pathname;k.sid=NLRUM.sessionId;k.isAsyncCallback=g;NLRUM.isFirstLoad&&(k.threadId=sessionStorage.getItem("nthreadid"),k.sOperationId=sessionStorage.getItem("soperationid2")||sessionStorage.getItem("soperationid"));NLRUM.clientScriptTime.push(k);50<=NLRUM.clientScriptTime.length&&
(NLRUM.sendData(NLRUM.beaconUrl,{clientscripttime:NLRUM.clientScriptTime}),NLRUM.clientScriptTime=[])};NLRUM=NLRUM||{};NLRUM.isDefined=function(a){return"undefined"!==typeof a};NLRUM.isFunction=function(a){return"function"===typeof a};NLRUM.mark=function(a,b){NLRUM.q.push(["mark",a,b||(new Date).getTime()])};NLRUM.measure=function(a,b,c){NLRUM.q.push(["measure",a,b,c||(new Date).getTime()])};NLRUM.getMarks=function(){return NLRUM.marks};NLRUM.getMeasures=function(){return NLRUM.measures};NLRUM.getStarts=function(){return NLRUM.starts};
NLRUM.setDefault=function(a,b){"undefined"===typeof NLRUM[a]&&(NLRUM[a]=b);return NLRUM[a]};NLRUM.generateUUID=function(){var a=(new Date).getTime();NLRUM.isDefined(performance)&&NLRUM.isFunction(performance.now)&&(a+=performance.now());return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var c=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"===b?c:c&3|8).toString(16)})};
NLRUM.isRumDisabled=function(){var a=document.cookie.match("(^|[^;]+)\\s*nlrum\\s*=\\s*([^;]+)");return"disabled"===(a?a.pop():"")};NLRUM.addEventListener=function(a,b,c){if("undefined"!==typeof window.attachEvent)return window.attachEvent("on"+a,b);if(window.addEventListener)return window.addEventListener(a,b,c)};NLRUM.processQ=function(){for(var a=NLRUM.q.length,b=0;b<a;b++){var c=NLRUM.q[b],d=c[0];"mark"===d?NLRUM.mark(c[1],c[2]):"measure"===d?NLRUM.measure(c[1],c[2],c[3]):"done"===d&&NLRUM.done(c[1])}};
NLRUM.sendData=function(a,b){NLRUM.isRumDisabled()||(b.beaconSentTime=(new Date).getTime(),NLRUM.makeRequest(a,b))};
NLRUM.makeRequest=function(a,b){return new Promise(function(c,d){var e=window.XMLHttpRequest?new XMLHttpRequest:window.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;e.open("POST",NLRUM.beaconUrl,!0);e.onload=function(){200<=this.status&&300>this.status?c(e.response):d({status:this.status,statusText:e.statusText})};e.setRequestHeader("Content-Type","application/json");e.setRequestHeader("X-Supress-Cookie-JSessionID","true");e.timeout=NLRUM.beaconUrlTimeout||1E4;e.send(JSON.stringify(b))})};
NLRUM.sendDataWithIncreasedInterval=function(){null!==NLRUM.browserSessionId&&clearTimeout(NLRUM.browserSessionId);NLRUM.doubleTimeInterval(function(){var a={};0<NLRUM.completedBrowserEntries.length&&(a.browsertime=NLRUM.completedBrowserEntries,NLRUM.completedBrowserEntries=[]);0<NLRUM.completedActionEntries.length&&(a.actionEntries=NLRUM.completedActionEntries,NLRUM.completedActionEntries=[]);0<NLRUM.unmatchedResources.length&&(a.resourcetime=NLRUM.unmatchedResources,NLRUM.unmatchedResources=[]);
0<Object.keys(a).length&&NLRUM.sendData(NLRUM.beaconUrl,a)},NLRUM.timeIntervalBase);setTimeout(function(){clearTimeout(NLRUM.browserSessionId)},NLRUM.timeIntervalMaxDuration)};NLRUM.doubleTimeInterval=function(a,b){function c(d){a();NLRUM.browserSessionId=setTimeout(c,b*d,2*d)}NLRUM.browserSessionId=setTimeout(c,b,2)};
NLRUM.mark=function(a,b){NLRUM.dprint("NLRUM.mark: "+a+", "+b);a?(NLRUM.marks[a]=parseInt(b||(new Date).getTime()),NLRUM.bPostMessage&&window.postMessage("NLRUM:mark:"+a+":"+b,NLRUM.targetOrigin)):NLRUM.dprint("Error: markName is undefined in NLRUM.mark.")};NLRUM.mergeObjects=function(){var a={};if(!arguments.length)return a;for(var b=0;b<arguments.length;b++)for(var c in arguments[b])a[c]=arguments[b][c];return a};
NLRUM.findStartTime=function(){var a=NLRUM.findStartWebTiming();a&&NLRUM.mark("starttime",a)};NLRUM.findStartWebTiming=function(){var a=void 0,b=NLRUM.getPerformanceObject();"undefined"!==typeof b&&"undefined"!==typeof b.timing&&"undefined"!==typeof b.timing.navigationStart&&(a=b.timing.navigationStart,NLRUM.dprint("NLRUM.findStartWebTiming: startTime = "+a));return a};
NLRUM.findStartCookie=function(){for(var a=document.cookie.split(" "),b=0;b<a.length;b++)if(0===a[b].indexOf("NLRUM=")){for(var c=a[b].substring(6).split("&"),d,e,f=0;f<c.length;f++)0===c[f].indexOf("s=")?d=c[f].substring(2):0===c[f].indexOf("r=")&&(e=c[f].substring(2),e=escape(document.referrer)==e);if(e&&d)return NLRUM.dprint("NLRUM.findStartCookie: startTime = "+d),d}};NLRUM.domContentLoaded=function(a){NLRUM.mark("domContent",(new Date).getTime());NLRUM.dprint("NLRUM.domContentLoaded: ")};
NLRUM.measure=function(a,b,c){NLRUM.dprint("NLRUM.measure: "+a+", "+b+", "+c);if(a){if("undefined"===typeof b)b="number"===typeof NLRUM.marks[a]?NLRUM.marks[a]:(new Date).getTime();else if("number"===typeof NLRUM.marks[b])b=NLRUM.marks[b];else if("number"!==typeof b){NLRUM.dprint("Error: unexpected startNameOrTime in NLRUM.measure: "+b);return}if("undefined"===typeof c)c=(new Date).getTime();else if("number"===typeof NLRUM.marks[c])c=NLRUM.marks[c];else if("number"!==typeof c){NLRUM.dprint("Error: unexpected endNameOrTime in NLRUM.measure: "+
c);return}NLRUM.starts[a]=parseInt(b,10);NLRUM.measures[a]=parseInt(c-b,10);NLRUM.bPostMessage&&window.postMessage("NLRUM:measure:"+a+":"+b+":"+c,NLRUM.targetOrigin)}else NLRUM.dprint("Error: episodeName is undefined in NLRUM.measure.")};NLRUM.clearMeasures=function(){NLRUM.measures={}};NLRUM.setDefault("utilLoaded",!0);NLRUM=NLRUM||{};NLRUM.done=function(a){NLRUM.mark("done");NLRUM.bSendBeacon&&NLRUM.sendPerfData();NLRUM.bPostMessage&&window.postMessage("NLRUM:done",NLRUM.targetOrigin);NLRUM.isFunction(a)&&a();NLRUM.recordPageLoadTime()};
NLRUM.sendPerfData=function(a,b){a=a||NLRUM.beaconUrl;var c=NLRUM.mergeObjects(NLRUM.getMeasures(),NLRUM.getMarks()),d={};NLRUM.isFirstLoad&&(c=NLRUM.mergeObjects(c,NLRUM.getNavigationTiming()));d.browsertime=[c];0<NLRUM.bResourceTimingDataCollection&&(c=NLRUM.getResourceTiming(),0<c.length&&(d.resourcetime=c),NLRUM.clearResourceTimings(!0));b&&(d.customParams=b);NLRUM.isFirstLoad=!1;NLRUM.clearMeasures();NLRUM.sendData(a,d)};
NLRUM.enableSPAFunctionalities=function(){NLRUM.isFirstLoad&&(NLRUM.pendingBrowserEntry=NLRUM.getBrowsertimeEntry("hard"),NLRUM.pendingBrowserEntry.done=Date.now(),NLRUM.pendingBrowserEntry.resources=NLRUM.getResourceTiming(),NLRUM.clearResourceTimings(!0),NLRUM.isFirstLoad=!1,setInterval(function(){NLRUM.completedBrowserEntries.length>=NLRUM.telemetryQueueSizeLimit&&NLRUM.sendData(NLRUM.beaconUrl,{browsertime:NLRUM.completedBrowserEntries});NLRUM.completedActionEntries.length>=NLRUM.telemetryQueueSizeLimit&&
(NLRUM.sendData(NLRUM.beaconUrl,{actionEntries:NLRUM.completedActionEntries}),NLRUM.completedActionEntries=[])},6E4),setInterval(function(){0<=NLRUM.pendingActions.length&&NLRUM.endPendingActionOverTimeLimit(NLRUM.actionPendingTimeLimit)},2E4));"soft"!==NLRUM.pendingBrowserEntry.linkType||NLRUM.pendingBrowserEntry.done||(NLRUM.pendingBrowserEntry.done=Date.now(),NLRUM.pendingBrowserEntry.resourceMatchEndTime=Date.now()+NLRUM.resourceWaitDuration)};
NLRUM.getBrowsertimeEntry=function(a){var b=NLRUM.mergeObjects(NLRUM.getMeasures(),NLRUM.getMarks());"hard"===a?(b=NLRUM.mergeObjects(b,NLRUM.getNavigationTiming()),b.linkType="hard"):(b.linkType="soft",b.resourceMatchEndTime=b.indirectnavigationstarttime+NLRUM.resourceWaitDuration,NLRUM.addESFieldsForBrowserTime(b));b.resources=[];return b};
NLRUM.addESFieldsForBrowserTime=function(a){void 0!==NLRUM.context&&(a.context=NLRUM.context);a.isFirstLoad=NLRUM.isFirstLoad;a.sHost=window.location.host;a.sHref=window.location.href;a.sid=NLRUM.sessionId;a.sReferrer=document.referrer;if(sessionStorage.getItem("url")){var b=sessionStorage.getItem("url").split("?",2);a.sUrl=b[0];a.sParams=1<b.length?b[1]:null;a.sUrl2=window.location.pathname;a.sParams2=window.location.search.substring(1)}else a.sUrl=window.location.pathname,a.sParams=window.location.search.substring(1);
a.userAgent=navigator.userAgent;a.sOperationId=sessionStorage.getItem("soperationid");a.sOperationId2=sessionStorage.getItem("soperationid2");a.sWhenceUrl=sessionStorage.getItem("whence");a.sMethod=sessionStorage.getItem("method")};
NLRUM.addBrowserMetrics=function(a){var b={};b.screenWidth=window.screen.width;b.screenHeight=window.screen.height;b.availWidth=window.screen.availWidth;b.availHeight=window.screen.availHeight;b.innerWidth=window.innerWidth;b.innerHeight=window.innerHeight;b.outerWidth=window.outerWidth;b.outerHeight=window.outerHeight;b.devicePixelRatio=window.devicePixelRatio;a.browserSettings=b};
NLRUM.getPerformanceObject=function(){return window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{}};
NLRUM.getNavigationTiming=function(){var a,b={},c=NLRUM.getPerformanceObject();if(c&&c.timing){NLRUM.dprint("This user agent supports NavigationTiming.","nt");var d=c.timing;b={connEnd:Math.floor(d.connectEnd),connStart:Math.floor(d.connectStart),domComplete:Math.floor(d.domComplete),domContentLoadedEvtEnd:Math.floor(d.domContentLoadedEventEnd),domContentLoadedEvtStart:Math.floor(d.domContentLoadedEventStart),domInteractive:Math.floor(d.domInteractive),domloading:Math.floor(d.domLoading),dmnLkEnd:Math.floor(d.domainLookupEnd),
dmnLkStart:Math.floor(d.domainLookupStart),fetchStart:Math.floor(d.fetchStart),loadEvtEnd:Math.floor(d.loadEventEnd),loadEvtStart:Math.floor(d.loadEventStart),navStart:Math.floor(d.navigationStart),redirEnd:Math.floor(d.redirectEnd),redirStart:Math.floor(d.redirectStart),reqStart:Math.floor(d.requestStart),respEnd:Math.floor(d.responseEnd),respStart:Math.floor(d.responseStart),unloadEvtEnd:Math.floor(d.unloadEventEnd),unloadEvtStart:Math.floor(d.unloadEventStart)};window.PerformanceNavigationTiming&&
(a=c.getEntriesByType("navigation")[0])&&(b.navigationType=a.type,b.redirCt=a.redirectCount);window.PerformancePaintTiming?(a=c.getEntriesByType("paint")[0])&&a.startTime&&(b.firstPaint=Math.floor(a.startTime+d.navigationStart)):0<d.msFirstPaint&&(b.firstPaint=Number(d.msFirstPaint));d.secureConnectionStart&&(b.secureConnStart=Math.floor(d.secureConnectionStart));NLRUM.addESFieldsForBrowserTime(b);NLRUM.addBrowserMetrics(b)}return b};
NLRUM.markIndirectStart=function(){var a=Date.now();NLRUM.mark("indirectnavigationstarttime",a);"soft"!==NLRUM.pendingBrowserEntry.linkType||NLRUM.pendingBrowserEntry.done||(NLRUM.pendingBrowserEntry.done=a,NLRUM.pendingBrowserEntry.status=NLRUM.status.attempted);"soft"===NLRUM.pendingBrowserEntry.linkType&&NLRUM.pendingBrowserEntry.resourceMatchEndTime>a&&(NLRUM.pendingBrowserEntry.resourceMatchEndTime=a);NLRUM.resourceMapping();NLRUM.completedBrowserEntries.push(NLRUM.pendingBrowserEntry);NLRUM.pendingBrowserEntry=
NLRUM.getBrowsertimeEntry("soft");NLRUM.sendDataWithIncreasedInterval()};NLRUM.setDefault("navigationLoaded",!0);NLRUM=NLRUM||{};NLRUM.sendResTiming=function(a){0<NLRUM.bResourceTimingDataCollection&&(a={resourcetime:a||NLRUM.getResourceTiming()},0!==a.resourcetime.length&&NLRUM.sendData(NLRUM.beaconUrl,a))};NLRUM.clearResourceTimings=function(a){window&&window.performance&&(window.performance.clearResourceTimings?window.performance.clearResourceTimings():window.performance.webkitClearResourceTimings&&window.performance.webkitClearResourceTimings());a&&sessionStorage.removeItem("resources")};
NLRUM.onRestimingBufferFull=function(){0<NLRUM.bResourceTimingDataCollection&&(0<NLRUM.pendingActions.length||0<NLRUM.actionEntries.length||0<Object.keys(NLRUM.pendingBrowserEntry).length&&NLRUM.pendingBrowserEntry.resourceMatchEndTime&&NLRUM.pendingBrowserEntry.resourceMatchEndTime>Date.now()?NLRUM.resourceMapping():(NLRUM.sendResTiming(),NLRUM.clearResourceTimings(!0)))};
NLRUM.resourceMapping=function(){NLRUM.updateCompletedActionEntries();var a=NLRUM.getResourceTiming();NLRUM.clearResourceTimings(!0);for(var b=[],c=0;c<a.length;c++){if(a[c].startTime>=NLRUM.pendingBrowserEntry.startTime&&a[c].startTime<NLRUM.pendingBrowserEntry.resourceMatchEndTime){NLRUM.pendingBrowserEntry.resources.push(a[c]);var d=!0}else d=NLRUM.mapResourceToAction(a[c]);d||b.push(a[c])}0<b.length&&(NLRUM.unmatchedResources=NLRUM.unmatchedResources.concat(b))};
NLRUM.mapResourceToAction=function(a){var b=!1,c;for(c=NLRUM.pendingActions.length-1;0<=c;c--){var d=NLRUM.pendingActions[c];if(a.startTime>=d.startTime){d.resources.push(a);b=!0;break}if(d.startTime<Date.now()-NLRUM.actionPendingTimeLimit)break}if(!b)for(c=NLRUM.actionEntries.length-1;0<=c;c--)if(d=NLRUM.actionEntries[c],a.startTime>=d.startTime){d.resources.push(a);b=!0;break}return b};
NLRUM.getResourceTiming=function(){var a={redirectStart:"redirStart",redirectEnd:"redirEnd",domainLookupStart:"dmnLkStart",domainLookupEnd:"dmnLkEnd",connectStart:"connStart",connectEnd:"connEnd",fetchStart:"fetchStart",secureConnectionStart:"secureConnStart",requestStart:"reqStart",responseStart:"respStart",responseEnd:"respEnd",startTime:"startTime"},b={domainLookupStart:"dmnLkStart",connectStart:"connStart",requestStart:"reqStart",responseStart:"respStart"},c={transferSize:"transferSize",encodedBodySize:"encodedBodySize"},
d=NLRUM.getPerformanceObject(),e,f;if(d&&NLRUM.isFunction(d.getEntriesByType)&&(e=d.getEntriesByType("resource"))){var h=0;d.timing&&d.timing.navigationStart&&(h=d.timing.navigationStart);d=e.filter(function(l){return!l.name.includes("NLRUMRequestHandler")&&!l.name.includes("session-status.json")&&!l.name.includes("PerfRenderTime")});var g={restiming:Array(d.length)};for(e=0;e<d.length;++e){g.restiming[e]={rtUrl:d[e].name,rtType:d[e].initiatorType,duration:Math.floor(d[e].duration),flags:{passTimingAllowCheck:!1}};
for(f in a)a.hasOwnProperty(f)&&0<=d[e][f]&&(g.restiming[e][a[f]]=Math.floor(h+d[e][f]),b.hasOwnProperty(f)&&!g.restiming[e].flags.passTimingAllowCheck&&0<d[e][f]&&(g.restiming[e].flags.passTimingAllowCheck=!0));for(f in c)c.hasOwnProperty(f)&&0<=d[e][f]&&(g.restiming[e][c[f]]=d[e][f]);NLRUM.addESFieldsForResourceTime(g.restiming[e])}}return g&&g.restiming?(sessionStorage.getItem("resources")&&(g.restiming=g.restiming.concat(JSON.parse(sessionStorage.getItem("resources")))),g.restiming):[]};
NLRUM.addESFieldsForResourceTime=function(a){void 0!==NLRUM.context&&(a.context=NLRUM.context);a.isFirstLoad=NLRUM.isFirstLoad;a.parentUrl=window.location.pathname;a.sid=NLRUM.sessionId;a.sOperationId=sessionStorage.getItem("soperationid")};NLRUM.setDefault("resourceLoaded",!0);NLRUM.endPendingActionOverTimeLimit=function(a){for(var b=Date.now(),c=NLRUM.pendingActions.length-1;0<=c;c--)NLRUM.pendingActions[c].startTime<b-a&&(NLRUM.actionEnd(NLRUM.pendingActions[c].actionId,{status:NLRUM.status.attempted},!1),NLRUM.completedActionEntries.push(NLRUM.actionEntries.pop()))};NLRUM.addFieldsForActionFlow=function(a){a.sid=NLRUM.sessionId;a.context=NLRUM.context;a.parentUrl=window.location.pathname;a.sHost=window.location.host;a.sHref=window.location.href;a.userAgent=navigator.userAgent};
NLRUM.getActionEntryById=function(a){for(var b=0;b<NLRUM.pendingActions.length;b++)if(NLRUM.pendingActions[b].actionId===a)return NLRUM.pendingActions[b]};
NLRUM.actionStart=function(a,b,c){if(!NLRUM.isRumDisabled()){var d=Date.now();c||("soft"===NLRUM.pendingBrowserEntry.linkType&&NLRUM.pendingBrowserEntry.resourceMatchEndTime>d&&(NLRUM.pendingBrowserEntry.resourceMatchEndTime=d),NLRUM.resourceMapping());a={actionId:NLRUM.generateUUID(),actionName:a,operationIds:[],resources:[],tags:b?b:[],startTime:c?Date.parse(c):d,isBackdated:!!c};NLRUM.addFieldsForActionFlow(a);NLRUM.pendingActions.push(a);c&&NLRUM.pendingActions.sort(function(e,f){return e.startTime-
f.startTime});NLRUM.sendDataWithIncreasedInterval();return a.actionId}};
NLRUM.actionEnd=function(a,b,c,d,e){if("undefined"!==typeof a&&!NLRUM.isRumDisabled()){var f="actionName baseLabel buildNo bundleId bundleName bundleVersion cartLines currencyCode customerSessionStatus dataContractVersion dateLabel device deviceId deviceName employeeId emvDeviceId errorMessage itemId itemQuantity locationId locationName operationIds paymentTypeId quickAddBarItemsCount sensorStability shopperInternalId siteUrl status transactionId visitorId shopperAnalyticsConsent workbookId workbookSorting workbookFilters workbookColumns workbookPage workbookRowCount guid".split(" "),h=
NLRUM.getActionEntryById(a);if("undefined"!==typeof h){e?h.endTime=Date.parse(e):b&&NLRUM.status.attempted===b.status||(h.endTime=Date.now());d&&(h.tags=h.tags.concat(d.filter(function(l){return 0>h.tags.indexOf(l)})));if("undefined"!==typeof b)for(var g in b)b.hasOwnProperty(g)&&-1!==f.indexOf(g)&&(h[g]=b[g]);NLRUM.actionEntries.push(h);a=NLRUM.pendingActions.indexOf(h);!c&&-1<a&&(NLRUM.pendingActions.splice(a,1),NLRUM.resourceMapping())}}};
NLRUM.updateCompletedActionEntries=function(){for(var a=-1,b=NLRUM.actionEntries.length-1;0<=b;b--)if(Date.now()-NLRUM.actionEntries[b].endTime>=NLRUM.resourceWaitDuration){a=b;break}0<=a&&(NLRUM.completedActionEntries=NLRUM.completedActionEntries.concat(NLRUM.actionEntries.slice(0,a+1)),NLRUM.actionEntries.splice(0,a+1))};NLRUM.setDefault("actionLoaded",!0);NLRUM=NLRUM||{};NLRUM.recordPageLoadTime=function(){NLRUM.pageLoadTime=(new Date).getTime()};
NLRUM.getTimeSpent=function(){var a={};a.sHost=window.location.host;a.sHref=window.location.href;a.sid=NLRUM.sessionId;a.sReferrer=document.referrer;if(sessionStorage.getItem("url")){var b=sessionStorage.getItem("url").split("?",2);a.sUrl=b[0];a.sParams=1<b.length?b[1]:null;a.sUrl2=window.location.pathname;a.sParams2=window.location.search.substring(1)}else a.sUrl=window.location.pathname,a.sParams=window.location.search.substring(1);a.userAgent=navigator.userAgent;a.sWhenceUrl=sessionStorage.getItem("whence");
a.sMethod=sessionStorage.getItem("method");a.timeSpent=(new Date).getTime()-NLRUM.pageLoadTime;return[a]};NLRUM.setDefault("timeSpentLoaded",!0);NLRUM=NLRUM||{};NLRUM.q=[];NLRUM.setDefault("bSendBeacon",1);NLRUM.setDefault("beaconUrl","/app/performance/NLRUMRequestHandler.nl");NLRUM.setDefault("beaconUrlTimeout",1E4);NLRUM.setDefault("bResourceTimingDataCollection",1);NLRUM.setDefault("bDebug",0);NLRUM.setDefault("autorun",1);NLRUM.setDefault("minClientScriptDuration",500);NLRUM.setDefault("absoluteMinClientScriptDuration",50);NLRUM.setDefault("telemetrySettingsCookieName","telemetrySettings");NLRUM.setDefault("isFirstLoad",!0);
NLRUM.sessionId=NLRUM.generateUUID();NLRUM.targetOrigin=document.location.protocol+"//"+document.location.hostname;NLRUM.bPostMessage=NLRUM.isDefined(window.postMessage);NLRUM.version="2.0";NLRUM.resourceWaitDuration=1E4;NLRUM.browserSessionId=null;NLRUM.timeIntervalBase=5E3;NLRUM.timeIntervalMaxDuration=3E5;NLRUM.telemetryQueueSizeLimit=10;NLRUM.actionPendingTimeLimit=12E4;
NLRUM.init=function(){NLRUM.status=Object.freeze({cancelled:"cancelled",completed:"completed",incomplete:"incomplete",attempted:"attempted",error:{user:"user-error",system:"system-error"}});NLRUM.marks={};NLRUM.measures={};NLRUM.starts={};NLRUM.clientScriptTime=[];NLRUM.pendingActions=[];NLRUM.actionEntries=[];NLRUM.completedActionEntries=[];NLRUM.pendingBrowserEntry={};NLRUM.completedBrowserEntries=[];NLRUM.unmatchedResources=[];NLRUM.addEventListener("beforeunload",NLRUM.beforeUnload,!1);NLRUM.processQ();
var a=NLRUM.getPerformanceObject();NLRUM.isDefined(a.onresourcetimingbufferfull)?a.onresourcetimingbufferfull=NLRUM.onRestimingBufferFull:NLRUM.isFunction(setInterval)&&NLRUM.isFunction(a.getEntriesByType)&&(NLRUM.sendResTiming(),NLRUM.clearResourceTimings(!0),setInterval(function(){if(50<=a.getEntriesByType("resource").length)NLRUM.onRestimingBufferFull()},1E4))};NLRUM.onload=function(a){NLRUM.mark("onload");NLRUM.dprint("NLRUM.onload: startTime = ");NLRUM.autorun&&NLRUM.done()};
NLRUM.beforeUnload=function(a){a={};0!==NLRUM.clientScriptTime.length&&(a.clientscripttime=NLRUM.clientScriptTime,NLRUM.clientScriptTime=[]);var b=NLRUM.getResourceTiming();0<b.length&&(a.resourcetime=b);b=NLRUM.actionEntries;b.length&&(a.actionEntries=b);a.timespent=NLRUM.getTimeSpent();a.beaconSentTime=(new Date).getTime();if(navigator.sendBeacon)navigator.sendBeacon(NLRUM.beaconUrl,JSON.stringify(a));else if(b=window.XMLHttpRequest?new XMLHttpRequest:window.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):
null)b.open("POST",NLRUM.beaconUrl,!1),b.setRequestHeader("Content-Type","application/json"),b.setRequestHeader("X-Supress-Cookie-JSessionID","true"),b.send(JSON.stringify(a))};NLRUM.dprint="undefined"!==typeof console&&"undefined"!==typeof console.log&&NLRUM.bDebug?function(a){console.log(a)}:function(a){};var loadDependencies=new Promise(function(a,b){NLRUM.utilLoaded&&NLRUM.navigationLoaded&&NLRUM.resourceLoaded&&NLRUM.actionLoaded&&NLRUM.timeSpentLoaded?a("All dependencies are loaded."):b("Failed to load dependencies.")});
loadDependencies.then(function(a){NLRUM.init();console.log(a)}).catch(function(a){console.log(a)});
//# sourceMappingURL=/assets/nlrum/3261946628.map