(function(k,q){function r(a,c,b,e=null){let d=l.PORTLET_CONTENT;d+=`?${h.WORKBOOK}=${a}`;d+=`&${h.VIEW_ID}=${c}`;d+=`&${h.PORTLET}=${h.Value.TRUE}`;b&&(d+=`&${h.ACTION}=${b}`);e&&(d+=`#${h.CHART_TYPE}=${e}`);return d}function t(a){let c=f.COMPONENT_MEDIUM;m[a]&&(c=m[a]);return c}function n(a,c,b=k.document){a=u(a,c);b.dispatchEvent(a)}function u(a,c,b=k.document){"undefined"!==typeof CustomEvent?b=new CustomEvent(a,{detail:c}):(b=b.createEvent("CustomEvent"),b.initCustomEvent(a,!1,!1,c));return b}
const l={SET_SETTINGS:"/app/center/card.nl",PORTLET_CONTENT:"/app/common/report/embedded.nl",WORKBOOK:"/app/common/report/report.nl"},h={WORKBOOK:"workbook",SELECTED_VIEW_ID:"selectedViewId",VIEW_ID:"viewId",CHART_TYPE:"chartType",PORTLET:"portlet",ACTION:"action",Value:{TRUE:"T"}},f={IFRAME:"portlet-analytics-component-iframe",ANALYTICS_PORTLET_WRAPPER:"ns-analytics-portlet-wrapper",GENERAL_PORTLET_WRAPPER:"ns-portlet-wrapper",COMPONENT_SHORT:"ns-dashboard-portlet-analytics-component--short",COMPONENT_MEDIUM:"ns-dashboard-portlet-analytics-component--medium",
COMPONENT_TALL:"ns-dashboard-portlet-analytics-component--tall",COMPONENT:"ns-dashboard-portlet-analytics-component",ANALYTICS_PORTLET_PIVOT_COLUMS:"n-usr-pivot-columns",ANALYTICS_PORTLET_PIVOT_GRID:"n-usr-pivot-grid"},m={["short"]:f.COMPONENT_SHORT,medium:f.COMPONENT_MEDIUM,tall:f.COMPONENT_TALL},g=NS.Portlet&&NS.Portlet.register("AnalyticsPortlet")||{};g.renderContent=function(){this.callClassMethod(g.superClassName,"renderContent");var a=this.getPortletContent();const c=a.find(`.${f.IFRAME}`);
var b=a.data();b&&b.workbookId&&b.viewId&&(this.switchContentLoaderOn(),this.data.workbookId=b.workbookId,this.data.viewId=b.viewId,this.data.customPortletName=b.customPortletName,this.data.viewName=b.viewName,this.data.chartType=b.chartType,this.data.action=b.action,this.data.customPortletName&&this.setTitle(this.data.customPortletName),this.isPivotPortletType="pivot"===b.type,this.isTablePortletType="tableview"===b.type,this.isPivotPortletType&&(this.computedTableHeight=35*b.numberOfRows),this.isTablePortletType&&
(this.computedTableHeight=36*b.numberOfRows+90),this.isPivotPortletType||this.isTablePortletType?this.isMaximized()?a.css("height","auto"):a.css("height",this.computedTableHeight):(b=t(b.portletSize),a.addClass(b)),a.closest(`.${f.GENERAL_PORTLET_WRAPPER}`).addClass(f.ANALYTICS_PORTLET_WRAPPER),a=r(this.data.workbookId,this.data.viewId,this.data.action,this.data.chartType),c.attr("src",a),c.on("load",()=>{setTimeout(()=>{this.switchContentLoaderOff()},300);const e=c.contents()[0];e.addEventListener("portletReloaded",
d=>{this.switchContentLoaderOff();this.callClassMethod(g.superClassName,"reload",d.detail.action,d.detail.params)});e.addEventListener("setPortletSetting",d=>{const p=d.detail;q.post(l.SET_SETTINGS,{dashboardid:this.dashboardIdentity.dashboardid,portletid:this.id,"action-target":"portlet",action:"set-analytics-portlet-settings",settings:JSON.stringify(p)}).catch(v=>{console.error(v);console.error(p)})});e.addEventListener("openWorkbook",()=>{this.openInWorkbook()});e.addEventListener("openSetup",
()=>{this.openSetup()});this.data.customPortletName||e.addEventListener("newTitle",d=>{this.setTitle(d.detail.title)})}))};g.getPortletContent=function(){return this.$body.find(`.${f.COMPONENT}`)};g.openInWorkbook=function(){if(this.data.workbookId&&this.data.viewId){var a=k.open;let c=l.WORKBOOK;c+=`?${h.WORKBOOK}=${this.data.workbookId}`;c+=`&${h.SELECTED_VIEW_ID}=${this.data.viewId}`;a.call(k,c)}};g.openSetup=function(){this.triggerAction("setup",{})};g.maximize=function(){var a=this.getPortletContent().find(`.${f.IFRAME}`).contents();
this.callClassMethod(g.superClassName,"maximize");n("maximizePortlet",{maximized:this.isMaximized()},a.get(0));if(this.isPivotPortletType||this.isTablePortletType)a=this.getPortletContent(),this.isMaximized()?a.css("height","auto"):a.css("height",this.computedTableHeight)};g.reload=function(a,c){const b=this.getPortletContent().find(`.${f.IFRAME}`).contents(),e=b.find('body [data-presenter="PortletErrorPresenter"]').length;"refresh"!==a||e?this.callClassMethod(g.superClassName,"reload",a,c):n("reloadPortlet",
{workbookId:this.data.workbookId,action:a,params:c},b.get(0))}})(window,NS.jQuery);
//# sourceMappingURL=/assets/analytics_dashboard_portlet/120801351.map