var NLListMachineOptions=new function(){var a={},b=function(){this.lastSortCol=-1;this.lastSortOrder=!0;this.lastSortDataType="TEXT";this.currentSortCol=-1;this.currentSortOrder=!0;this.currentSortDataType="TEXT";this.updateSortOptions=function(c,e,d){-1==this.currentSortCol&&(this.currentSortCol=c);this.currentSortCol!=c&&(this.lastSortCol=this.currentSortCol,this.lastSortOrder=this.currentSortOrder,this.lastSortDataType=this.currentSortDataType);this.currentSortCol=c;this.currentSortOrder=e;this.currentSortDataType=
d}};this.get=function(c){a.hasOwnProperty(c)||(a[c]=new b);return a[c]}};
function l_node(a,b,c,e,d,g,h,k,l){this.html=a;var n=NS.jQuery("<span>"+a+"</span>").find("input[type=text]:first");this.name=0<n.length?n.val():-1==a.indexOf(">")?a:a.substring(a.indexOf(">")+1,a.indexOf("</"));this.name=trim(this.name);this.row=b;this.dir_up=e;this.hier=d?d:"";this.type=c;null!=g&&0<g.length&&(this.html2=g,this.name2=-1==g.indexOf(">")?g:g.substring(g.indexOf(">")+1,g.indexOf("</")),this.name2=trim(this.name2),this.type2=h,this.dir_up2=k);this.linenum=l}
function l_isBlank(a){return"&nbsp;"==a||""==a}function l_sortnodes(a,b){var c=l_sortnodes2(a.name,b.name,a.type)*(a.dir_up?1:-1);return 0==c&&null!=a.type2&&null!=b.type2?l_sortnodes2(a.name2,b.name2,a.type2)*(a.dir_up2?1:-1):c}
function l_sortnodes2(a,b,c){return-1!=c.indexOf("CURRENCY")||"INTEGER"==c||"FLOAT"==c||"POSFLOAT"==c||"PERCENT"==c||"NUMERICKEY"==c?l_numnodes(a,b,c):"PRIORITY"==c?l_prioritynodes(a,b):"DATE"==c||"MMYYDATE"==c||"DATETIME"==c?l_datenodes(a,b,"DATETIME"==c):"TIMEOFDAY"==c?l_timenodes(a,b):l_charnodes(a,b)}function l_charnodes(a,b){return l_isBlank(a)||l_isBlank(b)?(a=l_isBlank(a),b=l_isBlank(b),a&&!b?1:b&&!a?-1:0):a.toLowerCase().localeCompare(b.toLowerCase())}
function l_numnodes(a,b,c){a=l_num(a,c);b=l_num(b,c);return a<b?-1:a==b?0:1}function l_getpriority(a){a=a.toLowerCase();if("l"==a.charAt(0))return 30;if("m"==a.charAt(0))return 20;if("h"==a.charAt(0))return 10}function l_prioritynodes(a,b){a=l_getpriority(a);b=l_getpriority(b);return a<b?-1:a==b?0:1}function l_datenodes(a,b,c){a=stringtodate(a).getTime();b=stringtodate(b).getTime();return isNaN(a)?1:isNaN(b)?-1:a<b?-1:a==b?0:1}
function l_timenodes(a,b){var c=new Date,e=c;c=l_time(a,c);e=l_time(b,e);return c<e?-1:c==e?0:1}function l_time(a,b){/([0-9][0-9]?)(:[0-5][0-9])\s?([AaPp])?[Mm]?/.exec(a);a=parseInt(RegExp.$1);b=parseInt(RegExp.$2.substr(1));return 60*("pm"==(0==RegExp.$3.length||"A"==RegExp.$3.toUpperCase()?"am":"pm")?a%12+12:a%12)+b}
function l_num(a,b){a=a.replace(window.number_blacklist_regex,"");a=a.replace(window.decimalseparator,".");var c=window.negativeprefix.length,e=window.negativesuffix.length;if(0<c&&a.substring(0,c)==window.negativeprefix||0<e&&a.substring(a.length-e,a.length)==window.negativesuffix)a="-"+a.substring(c,a.length-e);if(isNaN(a)||""==a)a="INTEGER"==b?"0":"0.0";return"INTEGER"==b?parseInt(a):parseFloat(a)}
function l_elem(a){var b=getBodyForm();return"undefined"!=typeof b&&"undefined"!=typeof b.elements?b.elements[a]:null}
function l_sort(a,b,c,e,d,g,h,k){null!=h&&(b=h);var l=-1,n=[],m,r=!0,t=!1;var f=getBodyForm();if(""==d||null==d)d="";else if(null!=l_elem(d+"sortidx")){l=f.elements[d+"sortidx"].value;if(l==a)l=-1;else{var p=f.elements[d+"sorttype"].value;var v="UP"==f.elements[d+"sortdir"].value}t=hasEncodedField(d,d+"seqnum")}f=document.getElementById(d+"dir"+a);-1!=f.className.indexOf("up")&&(r=!1);f.className="listheadersort"+(r?"up":"down");var q=document.getElementById(d+"header");for(m=0;m<q.cells.length;m++)m!=
a&&(f=document.getElementById(d+"dir"+m),null!=f&&(f.className="listheadersort"));f=NLListMachineOptions.get(d);f.updateSortOptions(a,r,b);-1==l&&(l=f.lastSortCol,v=f.lastSortOrder,p=f.lastSortDataType);q=!1;if("undefined"!=typeof k&&(f=document.getElementById(d+"row0"),null!=f&&(f=f.cells,"undefined"!=typeof f)))for(m=0;m<f.length;m++){var u=f[m].children[0];if("undefined"!=typeof u&&"hidden"==u.getAttribute("type")){q=!0;break}}u=q?k:a;for(k=0;;)if(f=document.getElementById(d+"row"+k),null!=f)q=
null!=h?f.cells[u].firstChild.innerHTML:f.cells[u].innerHTML,m=[],c?(f=l_elem("_hier"+k),e&&(q=f.value),n[k]=new l_node(q.toLowerCase(),m,b,r,f.value)):n[k]=-1!=l?new l_node(q.toLowerCase(),m,b,r,null,f.cells[l].innerHTML,p,v,t?findEncodedValue(d,d+"seqnum",k+1):-1):new l_node(q.toLowerCase(),m,b,r,null,null,null,null,t?findEncodedValue(d,d+"seqnum",k+1):-1),n[k].id=d+"row"+k,k++;else break;e=k;if(1<e){n.sort(l_sortnodes);l=document.getElementById(d+"row0");h=null;for(p=e-1;0<=p;--p)h=n[p],n[p].hasHighLight=
p%2,c&&(f=l_elem("_hier"+p),f.value=h.hier),t&&setEncodedValue(d,h.linenum,d+"seqnum",p+1),h=document.getElementById(h.id),h!=l&&h.parentNode.insertBefore(h,l),l=h;c=l_copyClassnamesToArray(document.getElementById(d+"row0"));t=l_copyClassnamesToArray(document.getElementById(d+"row1"));l=0<h.cells.length&&(0<=h.cells[0].className.indexOf("listtext")||0<=h.cells[0].className.indexOf("portlettext"));for(k=0;k<e;++k)h.id=d+"row"+k,l&&setUnsetHighlight(k,n,h,c,t),h=h.nextSibling}l_saveprefs(d,a,g,b,r)}
function setUnsetHighlight(a,b,c,e,d){for(var g=0;g<c.cells.length;++g)c.cells[g].className=b[a].hasHighLight?d[g]:e[g]}function l_copyClassnamesToArray(a){for(var b=Array(a.cells.length),c=0;c<b.length;++c)b[c]=a.cells[c].className;return b}function l_sortprefs(a,b,c,e){var d=!0;-1!=document.getElementById(c+"dir"+a).className.indexOf("up")&&(d=!1);l_saveprefs(c,a,e,b,d)}
function l_saveprefs(a,b,c,e,d){var g=getBodyForm();null!=a&&0<a.length&&null!=l_elem(a+"sortidx")&&(g.elements[a+"sortname"].value!=c&&(g.elements[a+"sort2name"].value=g.elements[a+"sortname"].value,g.elements[a+"sort2dir"].value=g.elements[a+"sortdir"].value),g.elements[a+"sortidx"].value=b,g.elements[a+"sortname"].value=c,g.elements[a+"sorttype"].value=e,g.elements[a+"sortdir"].value=d?"UP":"DOWN")}
function l_bold(a,b,c){a=document.getElementById(a+"row"+c);for(c=0;c<a.cells.length;c++){var e=a.cells[c].className;b&&-1!=e.indexOf("texttable")?e="textdark"+e.substring(e.indexOf("texttable")+9):b||-1==e.indexOf("textdark")||(e="texttable"+e.substring(e.indexOf("textdark")+8));a.cells[c].className=e}}function getBodyForm(){return document.forms.body_actions}function getFooterActionsForm(){return document.forms.footer_actions_form};
//# sourceMappingURL=/assets/legacy_listjs/3362449802.map