function getTranslatedString(c,a,b){b=b?b:"";return NS.Translations?NS.Translations.getTranslatedString(c,a)+b:parent.NS.Translations.getTranslatedString(c,a)+b}
function validate_html(c,a){if(null==c.value||0==c.value.length||null==a)return NS.form.setValid(!0),!0;var b=c.value.toLowerCase().replace(/\n/g,"").replace(/\t/g," "),k=!0,d="";if("html"==a)-1==b.indexOf("<html")?d=getTranslatedString("NLAlertContext.HTML_DOCUMENT_MUST_BEGIN_WITH_AN_HTML_TAG"):-1==b.indexOf("</html")?d=getTranslatedString("NLAlertContext.HTML_DOCUMENT_MUST_END_WITH_A_HTML_TAG"):b.indexOf("</html")<b.indexOf("<html")||b.indexOf("</html")<b.lastIndexOf("<")?d=getTranslatedString("NLAlertContext.HTML_TAG_IS_IN_THE_WRONG_PLACE"):
-1==b.indexOf("<body")?d=getTranslatedString("NLAlertContext.HTML_DOCUMENT_IS_MISSING_BODY_TAG"):b.indexOf("<body")<b.indexOf("<html")?d=getTranslatedString("NLAlertContext.BODY_TAG_IS_IN_THE_WRONG_PLACE"):-1==b.indexOf("</body")?d=getTranslatedString("NLAlertContext.HTML_DOCUMENT_IS_MISSING_BODY_TAG"):b.indexOf("</body")<b.indexOf("<body")||b.indexOf("</body")>b.indexOf("</html")?d=getTranslatedString("NLAlertContext.BODY_TAG_IS_IN_THE_WRONG_PLACE"):a="table";else if(-1!=b.indexOf("<html")||-1!=
b.indexOf("</html")||-1!=b.indexOf("<body")||-1!=b.indexOf("</body"))d=getTranslatedString("NLAlertContext.ONLY_AN_HTML_FRAGMENT_IS_EXPECTED_HERE_NOT_A_WHOLE_HTML_DOCUMENT__THERE_SHOULD_BE_NO_HTML_OR_BODY_TAGS");var f=0,l=0,e;if(""==d){var n=a.split(",");a="";for(var p=0;p<n.length;p++)a+="<"+n[p]+">";p=!0;n=0;for(var h,m,q=!1;-1!=(e=b.indexOf(q?a:"<",f));){e<m&&(e=m);f=e+1;var g=b.substring(e);-1!=g.indexOf(">")&&(g=g.substring(0,g.indexOf(">")));-1!=g.indexOf(" ")&&(g=g.substring(0,g.indexOf(" ")));
if("\x3c!--"==g)f=b.indexOf("--\x3e",f),-1==f&&(f=b.length);else if("<%"==g.substring(0,2)){g=b.indexOf("%>",f);e=char_pos_to_line_col(b,f-1);if(-1==g){d=getTranslatedString("NLAlertContext.MISSING_SUBSTITUTION_CLOSING_TAG_SEQUENCE__FOR_OPEN_TAG_AT_LINE_1_COLUMN_2",{1:e[0],2:e[1]});break}f=g}else{g+=">";l=g.length;m=e+l-1;for(var v,r=!1,t=!1;m<b.length;){var u=b.charAt(m);if("\\"==u)m+=2;else{if("'"==u)t||(r=!r)&&(v=m);else if('"'==u)r||(t=!t)&&(v=m);else if(">"==u&&!r&&!t)break;m++}}if(r||t){f=v+
1;l=1;d="Missing closing quote on tag attribute at character "+(f-e)+" for:\n"+b.substring(e,m+1);break}if("<td>"==g||"</td>"==g||"<tr>"==g||"</tr>"==g||"<table>"==g||"</table>"==g||"<script>"==g||"\x3c/script>"==g){"</"==g.substring(0,2)?n--:n++;if(0>n){e=char_pos_to_line_col(b,e);d=getTranslatedString("NLAlertContext.THERE_ARE_TOO_MANY_CLOSING_TABLE_TAGS_DUE_TO_TAG_1_AT_LINE_2_COLUMN_3",{1:g.toUpperCase(),2:e[0],3:e[1]});break}if(p){if("<script>"!=g&&"\x3c/script>"!=g&&(p=!1,-1==a.indexOf(g))){-1!=
a.indexOf("><")?(d=a.replace(/></g,"> or <"),d=getTranslatedString("NLAlertContext.THE_FIRST_TABLE_TAG_IN_YOUR_HTML_MUST_BE_ONE_OF_1_NOT_2",{1:d,2:g.toUpperCase()})):d=getTranslatedString("NLAlertContext.THE_FIRST_TABLE_TAG_IN_YOUR_HTML_MUST_BE_A_1_TAG_NOT_2",{1:a.toUpperCase(),2:g.toUpperCase()});break}}else if(-1==a.indexOf(g)){d=a.toUpperCase().replace(/></g,"> or <");e=char_pos_to_line_col(b,e);d=getTranslatedString("NLAlertContext.EXPECTED_1_AT_LINE_2_COLUMN_3_BUT_FOUND_A_4_TAG",{1:d,2:e[0],
3:e[1],4:g.toUpperCase()});break}"<table>"==g||"</tr>"==g?a="</table><tr><script>":"<td>"==g||"</table>"==g?a="</td><table><script>":"<tr>"==g||"</td>"==g?a="</tr><td><script>":"<script>"==g?(q=!0,h=a,a="\x3c/script>"):"\x3c/script>"==g&&(q=!1,a=h,h="")}}}""==d&&0<n&&(d=getTranslatedString("NLAlertContext.NOT_ALL_TABLE_TAGS_WERE_CLOSED_1__YOUR_HTML_IS_MISSING_A_CLOSING_2_TAG_AT_THE_END",{1:n,2:a.substring(0,a.indexOf(">"))}))}""!=d&&(alert(d),k=!1,setSelectionRange(c,f-1,f+l-1));return k}
function getTimeSelectorRange(c,a,b){a||(a=document.currentFCId);b||=document[NS.UI.AppUtil.timeSelectorToRangeMapJSName];if(c=b[c])if(a="start"in c?c:c[a])return a;return{start:null,end:null}}
function nlPopupGuides(c){if(NS.UI.Util.isNetscape){var a=window.screenX+30;var b=window.screenY+30}else a=top.screenLeft,b=top.screenTop;c=window.open("/images/guide/quicklooks.html?"+c,"popupguide","toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=0,resizable=0,left="+a+",top="+b+",height=410,width=800");NS.UI.Util.isNetscape||c.moveBy(a-c.screenLeft+30,b-c.screenTop+30);c.focus()}
function nlPopupGuide(c){var a=screen.height,b=screen.width,k=outerHt(),d=outerWd();if(NS.UI.Util.isNetscape){var f=window.screenX;var l=window.screenY}else f=window.screenLeft,l=window.screenTop;var e=d;1024>e&&(e=1024);f=e+300>b-f?b-(e+300):f;-4>f&&(f=-4);a=(768>a-l?a-768:l)-121;-4>a&&(a=-4);e=1024>d?1024:d;300>b-e&&(e=b-300);resizeTo(e,768>k?768:k);moveTo(f,a);getDocumentHeight();getDocumentWidth();window.open("/images/guide/quicklooks.html?"+c,"popupguide","toolbar=no,statusbar=no,menubar=no,resizableresizable=no,left="+
(f+e-4)+",top="+a+",height=700,width=300").focus()}function openMapWindow(c,a,b){a&&0!=a.length||(a="US");c=trim(c);if(0==c.length)alert(getTranslatedString("NLAlertContext.YOU_MUST_ENTER_AN_ADDRESS_BEFORE_YOU_CAN_VIEW_A_MAP"));else{for(var k,d=c.split("\n"),f,l=d.length-1;0<=l&&(f=trim(d[l]),0==f.length||(k=getCountry(f),null==k));l--);null==k&&(k=a);callMapFunctionByIndex(countryMap[k],c,b)}}
function nsResizeIframeToContent(c){var a=top.document.getElementById(c),b=a.contentWindow.document.body,k=NS.UI.AppUtil.contentBodyHeight,d=NS.UI.AppUtil.contentBodyWidth;if(!isNaN(k)&&0<k){var f=a.height!=k;a.height=k;nsDescendantOfType(b,"TABLE")&&!isNaN(d)&&(a.width=d);f&&nsResizeIframeToContent(c)}}
function uir_getAlertBoxHtml(c,a,b,k,d,f,l){if(NS.UI.Util.isRedwood)return uir_getRedwoodAlertBoxHtml(c,a,b,k,d,f,l);b!=NLAlertDialog.CONFIRMATION&&b!=NLAlertDialog.WARNING&&b!=NLAlertDialog.ERROR&&(b=NLAlertDialog.INFORMATION);c||(c=NLAlertDialog.defaultTitles[b],null==c&&(c=getTranslatedString("NLHeadingContext.ERROR")));var e=!1;d&&0<d.length&&(e=!0,f||=getTranslatedString("NLPagemessageContext.VISIT_THIS_HELP_TOPIC"));l||="";return"<div class='uir-alert-box "+NLAlertDialog.imageNames[b]+"'  width='"+
k+"' role='status'><div class='icon "+NLAlertDialog.imageNames[b]+"' ><img src='"+l+"/images/icons/messagebox/icon_msgbox_"+NLAlertDialog.imageNames[b]+".png' alt=''></div><div class='content'><div class='title'>"+c+"</div><div class='descr'>"+a+"</div>"+(e?"<div class='help'><a href=\""+d.replace(/"/g,"&#34")+'">'+f+"</a></div>":"")+"</div></div>"}
function uir_getRedwoodAlertBoxHtml(c,a,b,k,d,f){b!=NLAlertDialog.CONFIRMATION&&b!=NLAlertDialog.WARNING&&b!=NLAlertDialog.ERROR&&(b=NLAlertDialog.INFORMATION);c||(c=NLAlertDialog.defaultTitles[b],null==c&&(c=getTranslatedString("NLHeadingContext.ERROR")));k="<svg class='uir-alert-box-icon-image' role='img'><use href='/uiredwood/img/message/MessageIcon.svg#"+["CONFIRMATION","INFO","WARNING","ERROR"][b]+"'/></svg>";var l=!1;d&&0<d.length&&(l=!0,f||=getTranslatedString("NLPagemessageContext.VISIT_THIS_HELP_TOPIC"));
return'<div class="uir-alert-box uir-alert-box--'+NLAlertDialog.imageNames[b]+" "+NLAlertDialog.imageNames[b]+'" role="status"><div class="uir-alert-box-icon">'+k+'</div><div class="uir-alert-box-content"><div class="uir-alert-box-title">'+c+'</div><div class="uir-alert-box-description">'+a+'</div><div class="uir-alert-box-help">'+(l?'<a href="'+d.replace(/"/g,"&#34")+'">'+f+"</a>":"")+"</div></div></div>"}
function getAlertBoxHtml(c,a,b,k,d,f,l){b!=NLAlertDialog.CONFIRMATION&&b!=NLAlertDialog.WARNING&&b!=NLAlertDialog.ERROR&&(b=NLAlertDialog.INFORMATION);k||=500;c||(c=NLAlertDialog.defaultTitles[b],null==c&&(c=getTranslatedString("NLHeadingContext.ERROR")));var e=!1;d&&0<d.length&&(e=!0,f||=getTranslatedString("NLPagemessageContext.VISIT_THIS_HELP_TOPIC"));l||="";var n=NLAlertDialog.imageNames[b];return"<table class='uir-alert-box-legacy' cellpadding='0' cellspacing='0' border='0' style='margin:0px; min-height: 65px; border: 1px solid #417ed9;' width='"+
k+"' bgcolor='"+NLAlertDialog.backgroundColors[b]+"' data-type='"+n+"'><tr><td colspan='2' width='100%' height='15'></td></tr><tr><td align='left' valign='top'><div class='icon "+n+"'></div></td><td width='100%' valign='top'><div class='content'><b>"+c+"</b><br />"+a+(e?"<p align='right'> <img src='"+l+"/images/icons/messagebox/icon_help_green.png' style='height:12px; width:12px; display:block; vertical-align:middle' /> <a href=\""+d.replace(/"/g,"&#34")+'">'+f+"</a></p>":"")+"</div></td></tr><tr><td colspan='4' width='100%' height='15'></td></tr></table>"}
function scrollToField(c){try{var a=document.getElementById(NS.UI.AppUtil.fieldHighlightScroll+"_"+c);null!=a&&(document.body.scrollTop=findPosY(a)-30)}catch(b){}}
function checkMaxTotalLimit(c,a,b){if(""==a)c=parseFloat(nlapiGetFieldValue(c))+parseFloat(nlapiGetFieldValue(b));else{var k=!0;"undefined"!==typeof getMachine&&getMachine(a)&&getMachine(a).canUseOldFieldValue&&(k=getMachine(a).canUseOldFieldValue(nlapiGetCurrentLineItemIndex(a)));k=k?parseFloat(nlapiGetLineItemValue(a,b,nlapiGetCurrentLineItemIndex(a))||"0"):0;c=parseFloat(nlapiGetFieldValue(c))-k+parseFloat(nlapiGetCurrentLineItemValue(a,b))}return c>=getMaxTotalLimit()?(alert(getTranslatedString("NLAlertContext.TOTAL_AMOUNT_TOO_LARGE_ALERT")),
!1):!0}NS.UI.AppUtil.isBackendRequest||attachEventHandler("keydown",document,accessKeyHandler);function accessKeyHandler(c){var a=c.keyCode?c.keyCode:c.which;NS.UI.Util.isMac&&!c.ctrlKey||!c.altKey||18==a||(a=String.fromCharCode(a).toLowerCase(),a=NS.jQuery("[data-accesskey='"+a+"']"),0<a.length&&(a.click(),c.stopPropagation&&(c.stopPropagation(),c.preventDefault())))}
NS.UI.AppUtil.isBackendRequest||function(c){c&&c(document).ready(function(){function a(h){this.target=h;this.positionHandle=this.box=this.$tooltip=null}function b(h){if(h!==n&&h&&h.nodeType===Node.ELEMENT_NODE){n=h;var m=k(h);!p||!p.contains(n)||m&&m!==p.target?m?d(function(){f();document.contains(m)&&l(m)&&(p=new a(m),p.open())}):d(function(){f()}):null!==e&&(clearTimeout(e),e=null)}}function k(h){for(;h&&h!==document.documentElement;){if(l(h))return h;h=h.parentNode}return null}function d(h){null!==
e&&(clearTimeout(e),e=null);e=setTimeout(function(){e=null;h()},250)}function f(){p&&(p.close(),p=null)}function l(h){return h.getAttribute("data-ns-tooltip")&&!h.classList.contains("uir-machine-focused-cell")}var e=null,n=null,p=null;a.prototype.open=function(){var h=Math.min(c(window).width(),432),m=this.target.getAttribute("data-ns-tooltip").replace(/<[bB][rR]\s?\/?>/g,"\n");m=c("<div class='uir-machine-tooltip-text'/>").text(m);h=c("<div class='uir-machine-tooltip-body'/>").append(m).css({maxWidth:h+
"px"});m=c("<div class='uir-machine-tooltip-chevron'/>");this.$tooltip=c("<div class='uir-machine-tooltip'/>").append(m).append(h);this.$tooltip.appendTo(document.body);this.box=this.$tooltip.get(0).getBoundingClientRect();this.position();this.positionHandle=setInterval(this.update.bind(this),300)};a.prototype.close=function(){null!==this.positionHandle&&(clearInterval(this.positionHandle),this.positionHandle=null);this.$tooltip.detach();this.box=this.$tooltip=null};a.prototype.contains=function(h){return this.target.contains(h)||
this.$tooltip.get(0).contains(h)};a.prototype.position=function(){var h=this.target.getBoundingClientRect(),m=this.box,q=Math.min(h.top-10,m.height);this.$tooltip.css({top:Math.floor(h.top-q-10)+"px",left:Math.floor(h.left+h.width/2-m.width/2)+"px",maxHeight:q+"px"})};a.prototype.update=function(){document.contains(this.target)&&l(this.target)?this.position():f()};window.addEventListener("mousemove",function(h){b(h.target)},!0)})}(NS.jQuery);
//# sourceMappingURL=/assets/legacy_apputil/856623990.map