slavingUtil=function(){function w(c){function e(b,g,h,k){k=k?!1:!0;!0===b.isMachineField?a.setCurrentLineItemValue(b.machineName,b.fieldName,g,h,k):b.isMultiSelectField?a.setFieldValues(b.fieldName,g,h,k):a.setFieldValue(b.fieldName,g,h,k)}function f(b){null!==d.getFieldOptions()&&null===d.getFieldOptions().get(b.machineName,b.fieldName,b.lineNum)&&d.getFieldOptions().put(b.machineName,b.fieldName,b.lineNum,[]);return d.getFieldOptions().get(b.machineName,b.fieldName,b.lineNum)}var a=c.currentRecord,
d=c.util;this.setFieldNoSlaving=function(b,g){d.setFieldNoSlaving(b.machineName,b.fieldName,b.lineNum,g)};this.getValue=function(b){!0===b.isMachineField?b.ln&&-1!==b.ln?(b=a.getLineItemValue(b.machineName,b.fieldName,b.ln),b=null===b||void 0===b?"":b):b=a.getCurrentLineItemValue(b.machineName,b.fieldName):b=b.isMultiSelectField?a.getFieldValues(b.fieldName):a.getFieldValue(b.fieldName);return b};this.setValue=e;this.setSelectValue=function(b,g,h,k){g||""===g?e(b,g,k):!0===b.isMachineField?a.setCurrentLineItemText(b.machineName,
b.fieldName,h,k,!0):a.setText({fieldId:b.fieldName,text:h,fireFieldChange:k,noslaving:!0})};this.removeOption=function(b,g){b=f(b);if(0<b.length)if(g||0===g){a:{for(var h=0;h<b.length;h++)if(b[h].id==g){g=h;break a}g=-1}b.splice(g,1)}else b.splice(0,b.length)};this.insertOption=function(b,g,h){(b=f(b))&&b instanceof Array&&b.push({text:h,id:g})};this.isEditableSublist=d.isEditableSublist;this.isFieldMultiSelect=d.isFieldMultiSelect;this.returnEmptyIfNull=z;this.isValEmpty=A;this.setFavorites=d.setFavorites;
this.getCurrentLineItemIndex=function(b){return a.getCurrentSublistIndex({sublistId:b})};this.triggerPostSourcing=d.postSourcing}function v(){function c(a){return!0===a.isMachineField?nlapiGetLineItemField(a.machineName,a.fieldName,a.lineNum):nlapiGetField(a.fieldName)}function e(a,d){return a?document.forms[a+"_form"]:"undefined"!=typeof ftabs&&null!=ftabs[getFieldName(d)]?document.forms[ftabs[getFieldName(d)]+"_form"]:document.forms[0]}function f(a,d,b){a=getFormElement(a,getFieldName(d));null!=
a&&(null!=b?deleteOneSelectOption(a,b):deleteAllSelectOptions(a,window))}this.setFieldNoSlaving=function(a,d){if(a=c(a))a.noslaving=d};this.getValue=function(a){return!0===a.isMachineField?a.ln?z(nlapiGetLineItemValue(a.machineName,a.fieldName,a.ln)):nlapiGetCurrentLineItemValue(a.machineName,a.fieldName):a.isMultiSelectField?nlapiGetFieldValues(a.fieldName):nlapiGetFieldValue(a.fieldName)};this.setValue=function(a,d,b){!0===a.isMachineField?nlapiSetCurrentLineItemValue(a.machineName,a.fieldName,
d,b,!0):a.isMultiSelectField?nlapiSetFieldValues(a.fieldName,d,b,!0):nlapiSetFieldValue(a.fieldName,d,b,!0)};this.setSelectValue=function(a,d,b,g){!0===a.isMachineField?nlapiSetCurrentLineItemSelectValue(a.machineName,a.fieldName,d,b,g,getSlavingAsync()):nlapiSetSelectValue(a.fieldName,d,b,g,getSlavingAsync())};this.removeOption=function(a,d){if(!0===a.isMachineField){var b=a.fieldName;a=e(a.machineName,b);f(a,b,d)}else b=a.fieldName,a=e(null,b),f(a,b,d)};this.insertOption=function(a,d,b){if(!0===
a.isMachineField){var g=a.fieldName;a=e(a.machineName,g);g=getFormElement(a,getFieldName(g));null!=g&&addSelectOption(document,g,b,d)}else g=a.fieldName,a=e(null,g),g=getFormElement(a,getFieldName(g)),null!=g&&addSelectOption(document,g,b,d)};this.isEditableSublist=isEditMachine;this.isFieldMultiSelect=function(a,d,b){return(a=c({isMachineField:!!a,machineName:a,fieldName:d,lineNum:b}))?"multiselect"===a.getType():!1};this.serverCall=nsServerCall;this.returnEmptyIfNull=emptyIfNull;this.isValEmpty=
A;this.setFavorites=function(a,d,b){a=e(a,d);d=getFormElement(a,getFieldName(d));null!=d&&null!=b&&setFavoriteOptions(d,b)};this.getCurrentLineItemIndex=nlapiGetCurrentLineItemIndex}function B(c,e,f){var a=f?new w(f):new v,d=f?!1:!0,b=e.hasOwnProperty("lineNum")&&null!=e.lineNum?e.lineNum:null,g=e.sublistName||e.sublistId,h=C(c[m.QUERY_URL]),k=h[D.URL];h=h[D.PAYLOAD];if("T"===c[m.EDIT]){if((f=f?f.currentRecord.id:a.getValue({fieldName:"id"}))||0===f)h.id=String(f);"T"!==c[m.DISPLAY_ONLY]&&(h.e="T")}h.q=
e.queryFieldName;h.si=e.queryFieldValue;g&&(h.machine=g);0!=e.fieldspec.length&&(h.f=e.fieldspec);"T"===c[m.MULTILINE]&&0<b&&(h.ln=String(b));if(!F(d,c,b,h,a))return null;c[m.MASTER]&&""!==c[m.MASTER]&&(e=c[m.MASTER],c=e[m.FIELD_OBJECT.NAME],e=e.hasOwnProperty(m.FIELD_OBJECT.MACHINE)?e[m.FIELD_OBJECT.MACHINE]:null,h["si_"+c]=a.getValue({isMachineField:null!==e,machineName:e,fieldName:c,ln:b}));return{url:k,payload:h}}function F(c,e,f,a,d){e=e[m.AUX_FIELDS];for(var b=0;e&&b<e.length;b++){var g=e[b],
h=g.hasOwnProperty(m.FIELD_OBJECT.NAME)?g[m.FIELD_OBJECT.NAME]:"",k=g.hasOwnProperty(m.FIELD_OBJECT.MACHINE)?g[m.FIELD_OBJECT.MACHINE]:null,l=g.hasOwnProperty(m.FIELD_OBJECT.HTML_REF)?g[m.FIELD_OBJECT.HTML_REF]:null;k=d.getValue({isMachineField:null!==k,machineName:k,fieldName:h,ln:f});c&&!k&&0!==k&&""!==k&&(k=eval(l));if(G(g,k,"T"===g[m.FIELD_OBJECT.REQUIRED]))return!1;a["si_"+h]=k}return!0}function C(c){var e={};if(-1!==c.indexOf("?")){var f=c.split("?");c=f[0];if(0<f[1].length){f=f[1].split("&");
for(var a=0;a<f.length;a++)if(0<f[a].length){var d=f[a].split("=");e[d[0]]=String(d[1])}}}return{url:c,payload:e}}function G(c,e,f){var a=!0;c.hasOwnProperty(m.FIELD_OBJECT.REQUIRED_SCRIPT)&&(a=eval(c[m.FIELD_OBJECT.REQUIRED_SCRIPT])?!0:!1);c.hasOwnProperty(m.FIELD_OBJECT.IS_REQUIRED)&&c.isRequired&&(a=!0);c=e&&0!=e.length?!0:!1;return f&&a&&!c}function t(c){c=c.replace(/\\/g,"\\\\");c=c.replace(/'/g,"\\'");return c=c.replace(/"/g,'\\"')}function x(c){return"[object Function]"===Object.prototype.toString.call(c)}
function E(c){return c.map(function(e){return e&&2===e.length?{value:e[0],text:e[1]}:e})}function H(c,e,f){var a=e.hasOwnProperty(n.FIRE_FIELDCHANGE),d=e.hasOwnProperty(n.IS_CLIENT_SLAVING);c.setFieldNoSlaving(f,!a);var b=e[n.OPTIONS];if(b){var g=c.getValue(f),h=!1;c.removeOption(f);for(var k=0;k<b.length;k++){var l=b[k];c.insertOption(f,l[0],l[1]);g===l[0]&&(h=!0)}c.isValEmpty(e[n.VALUE])&&!c.isValEmpty(g)&&h&&c.setValue(f,g,!1)}(b=e[n.FAVORITES])&&c.setFavorites(f.machineName,f.fieldName,E(b));
if(null==e[n.NO_OVERRIDE]||c.isValEmpty(c.getValue(f)))if(b="boolean"===typeof e[n.CONDITION]?e[n.CONDITION]:eval(e[n.CONDITION]),!e.hasOwnProperty(n.CONDITION)||b)e.hasOwnProperty(n.TEXT)?c.setSelectValue(f,e[n.VALUE],e[n.TEXT],a,d):e.hasOwnProperty(n.VALUE)&&c.setValue(f,e[n.VALUE],a,d)}function I(c,e){var f="undefined"!=typeof ftabs&&null!=ftabs[getFieldName(c)]?document.forms[ftabs[getFieldName(c)]+"_form"]:document.forms[0];c=getFormElement(f,getFieldName(c));return null!=c?"multiselect"===e?
getMultiDropdown(c,window).getValues():getDropdown(c,window).getValues():null}function J(c,e){var f="undefined"!=typeof ftabs&&null!=ftabs[getFieldName(c)]?document.forms[ftabs[getFieldName(c)]+"_form"]:document.forms[0];c=getFormElement(f,getFieldName(c));return null!=c?"multiselect"===e?getMultiDropdown(c,window).textArray:getDropdown(c,window).getTexts():null}function K(c,e,f){c=getFormElement(document.forms[c+"_form"],getFieldName(e));return null!=c?"multiselect"===f?getMultiDropdown(c,window).getValues():
getDropdown(c,window).getValues():null}function L(c,e,f){c=getFormElement(document.forms[c+"_form"],getFieldName(e));return null!=c?"multiselect"===f?getMultiDropdown(c,window).textArray:getDropdown(c,window).getTexts():null}function A(c){if(null===c||void 0===c)return!0;c=String(c);return 0===c.length||!/\S/.test(c)}function z(c){return null!=c?c:""}var m={QUERY_URL:"queryurl",EDIT:"edit",DISPLAY_ONLY:"displayonly",AUX_FIELDS:"auxfields",MULTILINE:"ln",MASTER:"master",FIELD_OBJECT:{NAME:"name",MACHINE:"machine",
HTML_REF:"htmlReference",REQUIRED:"required",REQUIRED_SCRIPT:"requiredScript",IS_REQUIRED:"isRequired"}},D={URL:"url",PAYLOAD:"payload"},n={NAME:"name",MACHINE_NAME:"machine",FIRE_FIELDCHANGE:"firechange",IS_CLIENT_SLAVING:"isClientSlaving",OPTIONS:"options",VALUE:"value",TEXT:"text",NO_OVERRIDE:"nooverride",CONDITION:"condition"};return{cleanupQueryURL:C,getQueryRequest:B,getURL:function(c,e){e=B(c,e,void 0);c=e.url;e=e.payload;-1==c.indexOf("?")&&(c+="?");var f=!0,a;for(a in e)f?f=!1:c+="&",c=0===
a.indexOf("si_")||"q"===a||"si"===a||"id"===a?c+a+"="+encodeURIComponent(emptyIfNull(e[a])):c+a+"="+emptyIfNull(e[a]);return c},processSlavingValues:function(c,e,f){for(var a=e?new w(e):new v,d=0;c&&d<c.length;d++){var b=c[d],g=b[n.NAME],h=b.hasOwnProperty(n.MACHINE_NAME),k=h?b[n.MACHINE_NAME]:null,l=h?a.getCurrentLineItemIndex(k):-1;h={isMachineField:h,machineName:k,fieldName:g,lineNum:l};h.isMultiSelectField=a.isFieldMultiSelect(k,g,l);if(x(b))f?f(b.toString()+";"+b.name+"();"):b(a);else try{H(a,
b,h)}catch(p){if(a instanceof v)a.serverCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Excepion in processing values",p.msg+",path =  "+(e?"":window.location.pathname)]);else throw p;}finally{null==e&&a.setFieldNoSlaving(h,!1)}}},verifySlavingValues:function(c,e){try{for(var f=0;c&&f<c.length;f++)for(var a=0;e&&a<e.length;a++){var d=e[a];if(!(x(d)||d.name!=c[f][0]||null!=d.machine&&d.machine!=c[f][1]||null==d.machine&&""!=c[f][1])){var b=d.options,g=nlapiGetLineItemField(d.machine,
d.name);if(null!=d.machine){if(null!=b){var h=K(d.machine,d.name,g.type),k=L(d.machine,d.name,g.type);if(h.length!=b.length)nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json option Length mismatch","Options length do not match. Field name:"+d.name+" ,path = "+window.location.pathname]);else for(var l=0;b&&l<b.length;l++){var p=b[l],y=t(h[l]),u=t(k[l]);u=u.replace("\n","");if(p[0]!=y){nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json option Value mismatch",
"Options slaving value do not match. Field name:"+d.name+" jsonValue ="+p[0]+" legacyValue = "+h[l]+" ,path = "+window.location.pathname]);break}if(p[1]!=u){nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json option Value mismatch","Options slaving text do not match. Field name:"+d.name+" jsonValue ="+p[1]+" legacyValue = "+k[l]+" ,path = "+window.location.pathname]);break}}}if(null==d.nooverride&&(null==d.condition||eval(d.condition))){var q=nlapiGetCurrentLineItemValue(d.machine,
d.name);q=t(q);null!=d.value&&d.value!=q&&nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json Value mismatch","Value slaving result do not match. Field name:"+d.name+", jsonText = "+d.value+", actualValue  = "+q+" ,path = "+window.location.pathname]);if(null!=d.text){var r=nlapiGetCurrentLineItemText(d.machine,d.name);r=t(r);d.text!=r&&nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json Value mismatch","Value slaving result do not match. Field name:"+
d.name+", jsonText = "+d.text+", actualValue  = "+r+" ,path = "+window.location.pathname])}}}else{q=nlapiGetFieldValue(d.name);q=t(q);b=d.options;g=nlapiGetField(d.name);if(null!=b)if(h=I(d.name,g.type),k=J(d.name,g.type),h.length!=b.length)nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json option Length mismatch","Options length do not match. Field name:"+d.name+" ,path = "+window.location.pathname]);else for(l=0;b&&l<b.length;l++){p=b[l];y=t(h[l]);u=t(k[l]);u=u.replace("\n",
"");if(p[0]!=y){nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json option Value mismatch","Options slaving value do not match. Field name:"+d.name+" jsonValue ="+p[0]+" legacyValue = "+h[l]+" ,path = "+window.location.pathname]);break}if(p[1]!=u){nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json option Value mismatch","Options slaving text do not match. Field name:"+d.name+" jsonValue ="+p[1]+" legacyValue = "+u[l]+" ,path = "+window.location.pathname]);
break}}null!=d.nooverride||null!=d.condition&&!eval(d.condition)||(null!=d.value&&d.value!=q&&nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json Value mismatch","Value slaving result do not match. Field name:"+d.name+", jsonText = "+d.value+", actualValue  = "+q+" ,path = "+window.location.pathname]),null!=d.text&&(r=nlapiGetFieldText(d.name),r=t(r),d.text!=r&&nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Json Value mismatch","Value slaving result do not match. Field name:"+
d.name+", jsonText = "+d.text+", actualValue  = "+r+" ,path = "+window.location.pathname])))}}}}catch(M){nsServerCall("/app/common/scripting/nlapijsonhandler.nl","logSlavingError",["Excepion in verifying values",M.msg+" ,path = "+window.location.pathname])}},redrawEditMachines:function(c){for(var e in c){var f=c[e];if(null!=f.edit&&(null==f.nooverride||1==document.forms[0].elements["next"+e+"idx"].value)){for(var a=f.data,d="",b=0;a&&b<a.length;b++){for(var g=a[b],h=0;g&&h<g.length;h++)""!=d&&(d+=
String.fromCharCode(1)),d+=g[h];b!=a.length-1&&(d+=String.fromCharCode(2))}document.forms[0].elements[e+"data"].value=d;clearLineArray(name);document.forms[0].elements["next"+e+"idx"].value=null==a?1:a.length+1;document.forms[0].elements[e+"valid"].value="T";setMachineContentUpdated(e,!0);clearLineArray(name);null!=parent.document.forms.main_form.elements[e+"loaded"]&&(parent.document.forms.main_form.elements[e+"loaded"].value="T");null!=parent.document.forms.main_form.elements[e+"dotted"]&&(parent.document.forms.main_form.elements[e+
"dotted"].value="T");null!=window[e+"_machine"]&&(window[e+"_machine"].refresheditmachine(!0),window[e+"_machine"].recalc());a=parent.document.getElementById(e+"lnkdot");null!=a&&(a.style.display="")}x(f.metadata)&&f.metadata.call()}},applyFavorites:function(c,e){if(c){var f=e?new w(e):new v;Object.keys(c).forEach(function(a){a=c[a];var d=a[n.OPTIONS];d&&f.setFavorites(a[n.MACHINE_NAME]||null,a[n.NAME],E(d))})}}}}();"function"==typeof Object.freeze&&(slavingUtil=Object.freeze(slavingUtil));
//# sourceMappingURL=/assets/legacy_slavingutil/494223087.map